# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Competence Section
  description: "A section designed to highlight key competencies or features with a rich visual and textual description, suitable for detailing services or capabilities."
  icon: "bar_chart"
  tags:
    - competence
    - services
    - features

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Competence Description"
  subTitle: "Why Choose Us"
  items:
    - title: "Innovative Solutions"
      image: "https://cdn.rareblocks.xyz/collection/clarity/images/features-v2/3/feature.png"
      description: "We offer creative and practical solutions tailored to meet your unique needs."
    - title: "Experienced Professionals"
      image: "https://cdn.rareblocks.xyz/collection/clarity/images/features-v2/3/feature.png"
      description: "Our team consists of highly skilled professionals with extensive industry experience."
    - title: "Customer-Centric Approach"
      image: "https://cdn.rareblocks.xyz/collection/clarity/images/features-v2/3/feature.png"
      description: "We prioritize your needs and satisfaction above everything else."
