source: /
paths:
  uploads: public
  static: public
  collections: ''
  data: data
  layouts:
timezone: Etc/UTC
collections_config:
  locales: 
    path: _locales
    disable_add: true
    disable_add_folder: true
  data:
    path: data
    disable_add: true
    disable_add_folder: true'
  pages:
    path: src/content/pages
    url: "/[slug]/"
    output: true
    icon: wysiwyg
    disable_add_folder: true
    _enabled_editors:
      - visual
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Site Settings
    collections:
      - data
      - site_navigation
      - theme_palette
