source: /
paths:
  uploads: assets/uploads
  static: public
  collections: ''
  data: data
  layouts:
timezone: Etc/UTC
collections_config:
  data:
    path: data
    disable_add: true
    disable_add_folder: true'
  pages:
    path: src/pages
    output: true
pages:
  path: src/pages
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Site Settings
    collections:
      - data
      - site_navigation
      - theme_palette
