# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Hero
  description: "A dynamic hero section with customizable title, subtitle, and a list of features or services, ideal for showcasing key information at the top of a page."
  icon: "cottage"
  tags:
    - hero
    - marketing
    - features

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Email Marketing is the Future for Growing Your Business Revenues"
  subTitle: "Discover Our Platform"
  items:
    - title: "Tincidunt pulvinar"
      description: "Ut enim ad minima veniam, quis nostrum autem vel eum iure reprehenderit exercitem."
    - title: "Vestibulum sodales"
      description: "Nunc volutpat odio facilisis fermentum parturient, amet risus accumsan lacus."
    - title: "Aenean ligula"
      description: "Phasellus et ligula in dui cursus congue sed quis sapien."

