# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Section
  description: "An engaging section that combines imagery with text to tell visitors about the organization's mission or background."
  icon: "info_circle"
  tags:
    - about
    - introduction
    - company

# Defines the structure of this component, as well as the default values
blueprint:
  title: "About Us and References"
  subTitle: "About Us"
  buttonText: "Call To Action" 
  buttonHref: "#"
  image: "https://landingfoliocom.imgix.net/store/collection/saasui/images/features/9/feature-9.png"
  description: "“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare non sed est cursus. Vel hac convallis ipsum, facilisi odio pellentesque bibendum viverra tempus.”"
  author: "Grandon Jones"
