# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Form
  description: "A user-friendly form allowing site visitors to send messages directly through the website."
  icon: "contact_mail"
  tags:
    - contact
    - form
    - interaction

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Contact Us"
  subTitle: "Lorem Ipsum"
  buttonText: "Call To Action"
