# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Section
  description: "A visually striking section that introduces the site with a large image, a compelling headline, and a clear call-to-action."
  icon: "visibility"
  tags:
    - hero
    - headline
    - cta

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Sed ut perspiciatis unde omnis"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula massa in enim luctus. Rutrum arcu."
  buttonText: "Click To Learn More"
  buttonHref: "#"
