# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Integration Logos
  description: "A section displaying partnership or integration logos with a central text block highlighting collaborative strengths."
  icon: "partnerships"
  tags:
    - integrations
    - partnerships
    - logos

# Defines the structure of this component, as well as the default values
blueprint:
  title: "We build on"
  subTitle: "LOREM IPSUM"
  text: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur."
  leftLogos: "https://cdn.rareblocks.xyz/collection/clarity/images/integrations/3/left-logos.png"
  rightLogos: "https://cdn.rareblocks.xyz/collection/clarity/images/integrations/3/right-logos.png"
  topLogos: "https://cdn.rareblocks.xyz/collection/clarity/images/integrations/3/top-logos.png"
  bottomLogos: "https://cdn.rareblocks.xyz/collection/clarity/images/integrations/3/bottom-logos.png"
