# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Reference Applications
  description: "A visually appealing section designed to showcase reference applications or case studies, highlighting key solutions or projects."
  icon: "folder_open"
  tags:
    - reference
    - applications
    - case studies

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Reference Applications"
  subTitle: "Lorem Ipsum"
  buttonText: "Call To Action" 
  buttonHref: "#"
  items:
    - title: "Tellus pharetra sit convallis vel"
      description: "Tellus pharetra sit convallis vel, fermentum dignissim cras in."
      image: "https://cdn.rareblocks.xyz/collection/clarity/images/features-v2/3/feature.png"
      extended_description: "Consectetur adipis cing elit. Mattis a, tincidunt pulvinar sodales. Quis tellus vel eget in nulla odio. Tellus pharetra sit convallis vel, fermentum dignissim cras in."
    - title: "Tellus pharetra sit convallis vel"
      description: "Tellus pharetra sit convallis vel, fermentum dignissim cras in."
      image: "https://cdn.rareblocks.xyz/collection/clarity/images/features-v2/3/feature2.png"
      extended_description: "Lorem ipsum dolor sit amet, consectetur adipis cing elit. Mattis a, tincidunt pulvinar sodales. Quis tellus vel eget in nulla odio."
    - title: "Tellus pharetra sit convallis vel"
      description: "Tellus pharetra sit convallis vel, fermentum dignissim cras in."
      image: "https://cdn.rareblocks.xyz/collection/clarity/images/features-v2/3/feature3.png"
      extended_description: "Mattis a, tincidunt pulvinar sodales. Quis tellus vel eget in nulla odio. Tellus pharetra sit convallis vel, fermentum dignissim cras in."
  bottomBlockTitle: "Are you curious about what AI can do for you?"
  bottomBlockDescription: "We will prepare a free demo session based on your business needs and requirements. Request a demo session today and we will build a free Generative AI prototype for you!"
 
