# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Application Description
  description: "Showcases various application features or services in a detailed and visually engaging timeline format."
  icon: "timeline"
  tags:
    - application
    - timeline
    - services

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Application Description"
  subTitle: "Lorem Ipsum"
  items:
    - image: "/image-4.webp"
      title: "Quia dolor sit amet"
      description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed qui."
    - image: "icon-path-2.svg"
      title: "Quia dolor sit amet"
      description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed qui."
    - image: "icon-path-3.svg"
      title: "Quia dolor sit amet"
      description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed qui."
    - image: "icon-path-4.svg"
      title: "Quia dolor sit amet"
      description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed qui."
