# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Form
  description: "A user-friendly form allowing site visitors to send messages directly through the website."
  icon: "contact_mail"
  tags:
    - contact
    - form
    - interaction

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Watch our Intelligent Industries Podcast"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  buttonText: "Call To Action"
  buttonHref: "/contact"
  image: "/image-1.webp"
  icons:
    - image: "/image-4.webp"
      href: "#"
    - image: "/icon-path-2.svg"
      href: "#"
    - image: "/icon-path-3.svg"
      href: "#"

